all:
	@make -C src
	@cp src/takuzu .

clean: 
	@rm -f *.o takuzu


help:
	@echo "Usage: "
	@echo "make [all]\t Build the software"
	@echo "make clean \t Remove all files generated by make"
	@echo "make help\t display this help"


.PHONY: all clean help
