all:
	@make -C src
	@cp src/takuzu .

clean: 
	@rm -f src/*.o takuzu src/takuzu
test:
	@cd tests
	@tests/tester.sh
help:
	@echo "Usage: "
	@echo "make [all]\t Build the software"
	@echo "make clean\t Remove all files generated by make"
	@echo "make test\t Execute testing script (tester.sh in tests folder)"
	@echo "make help\t display this help"


.PHONY: all clean help
